### ISSUE TITLE
new resource: github_actions_repository_permissions

### ISSUE THREAD

**Issue by StephenWithPH** [integrations/terraform-provider-github#1008]
It would be useful to have a resource `github_actions_repository_permissions` which mirrors the existing resource `github_actions_organization_permissions` but for a single repository rather than the entire GitHub organization.

This would allow repository admins to manage Actions on a repo regardless of their organization-level permissions.

**Comment by br3ndonland** [comment]
It would be great to have a `github_actions_repository_permissions` resource.

In addition to the configuration settings in the existing `github_actions_organization_permissions` resource, there are some settings that apply only at the repo level.

[Actions access](https://docs.github.com/en/enterprise-cloud@latest/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-access-to-components-in-an-internal-repository) would be a helpful one. The setting is at Actions -> General -> Access.

<img src="https://docs.github.com/assets/cb-16314/images/help/repository/actions-general-tab.png" alt="GitHub repo settings Actions general tab" width="600px" />

<img src="https://docs.github.com/assets/cb-81457/images/help/settings/actions-access-settings.png" alt="GitHub repo settings Actions access" width="600px" />

This setting enables [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) for internal repos in an organization or enterprise. Instead of copying and pasting GitHub Actions YAML into every repo, workflows can be kept in one repo, and called from the other repos.

**Comment by nfcopier** [comment]
It looks like this has already been resolved. https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_repository_permissions

**Comment by StephenWithPH** [comment]
@nfcopier : thanks for the heads-up.

This resource showed up in https://github.com/integrations/terraform-provider-github/releases/tag/v5.9.0; it was addressed in #1339.

Closing.
