### ISSUE TITLE
Constantly getting errors when organization secrets are removed from repositories

### ISSUE THREAD

**Issue by nikolay** [integrations/terraform-provider-github#1034]
We constantly get the error below when removing an organization secret from a repo:

### Terraform Version
`v1.1.3`
`v1.1.4`

### Debug Output
```
Terraform v1.1.3
on linux_amd64
Initializing plugins and modules...
github_actions_organization_secret.secrets["[REDACTED]"]: Modifying... [id=[REDACTED]]
github_actions_organization_secret.secrets["[REDACTED]"]: Modifying... [id=[REDACTED]]
github_actions_organization_secret.secrets["[REDACTED]"]: Modifying... [id=[REDACTED]]
github_actions_organization_secret.secrets["[REDACTED]"]: Modifying... [id=[REDACTED]]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ github_actions_organization_secret.secrets["[REDACTED]"],
│ provider "provider[\"registry.terraform.io/integrations/github\"]" produced
│ an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
...
```

**Comment by nikolay** [comment]
@jcudit Any idea about this? Pretty much we always need to apply due to those constant errors!

**Comment by jcudit** [comment]
🙇🏾 for reporting this.  Hmm, was there a date / version this started? 🤔 possibly due to a `go-github` bump as we haven't modified this resource lately.

**Comment by nikolay** [comment]
Let me try to see, but's been happening for at least a month. I kept upgrading in secret hopes it will go away, but it doesn't.

**Comment by nikolay** [comment]
@jcudit It's been happening since `~> 4.18.2`, at least.

**Comment by nikolay** [comment]
@jcudit This is very annoying... Can you please look into it? It just defeats the whole purpose of IaC if all commits lead to errors and actually break things, which have to be fixed with a re-apply.

**Comment by janakerman-form3** [comment]
I'm seeing this same error under different circumstances, after simply adding a `github_actions_organization_secret` via Terraform. The first plan + apply worked successfully but now all subsequent applies in the workspace are now failing with the same error as above.

Please let me know if you'd rather I create a separate issue instead of tagging long here.

**Comment by arbourd** [comment]
I'm pretty sureI know what is causing this. I've done some hacking on Terraform providers before and "inconsistent result" implies that the object exists at the beginning of the create, but **doesn't** at the end of the create (when performing a confirming get). This is usually related to the unique ID that terraform gets and uses to manage the state of the object.

Here's what I'm thinking happens when you modify a secret:
- When you modify the state of a secret (within or outside of Terraform) this provider no longer can diff / manage it
- When the secret has been modified, the provider gets back an ID that doesn't make sense (as per error)
- Reapplying the entire workspace will solve this by forcing a creation of the secret from scratch

This is very similar to #974 where modifying the `selected_repository_ids` forces recreation of the secrets endlessly.

This is either a bug where we aren't handling state properly for the modification of secrets, or, it's not fixable where the GitHub API forces secret recreation on modification. If it's the latter, perhaps the solution is that we don't allow any modification of the secret and any change forces a full creation.

**Comment by jandroav** [comment]
Hey! I was wondering if just manually deleting the affected secret and then running the `apply` will create it from scratch, just to avoid that error. I know the next time it will throw the error again.
