### ISSUE TITLE
github_user_invitation_accepter requires invitation_id and fails if collaborators have already accepted

### ISSUE THREAD

**Issue by HariSekhon** [integrations/terraform-provider-github#1157]
### Terraform Version

 v1.1.3

### Affected Resource(s)

- github_user_invitation_accepter

### Terraform Configuration Files

pretty much straight off this doc page:

https://registry.terraform.io/providers/integrations/github/latest/docs/resources/user_invitation_accepter

```hcl
resource "github_repository_collaborator" "my-ci" {
  repository = github_repository.repo.id
  username   = "my-ci"
  permission = "${var.ci_permission}"
}
provider "github" {
  alias = "invitee"
  token = var.ci_github_token
}
resource "github_user_invitation_accepter" "my-ci" {
  provider = github.invitee
  invitation_id = github_repository_collaborator.my-ci.invitation_id 
}
```

### Debug Output

https://gist.github.com/HariSekhon/22dd17a57951c8c8110d0ba10782da1e

### Expected Behavior
Ignore if the collaborator has already accepted

### Actual Behavior
Gets 404 errors or says field is not set when it's being passed `github_repository_collaborator.my-ci.invitation_id`

### Steps to Reproduce

1. `terraform apply`

**Comment by morremeyer** [comment]
This is a bug we also encounter. It would be great if it could be resolved. I'll try to take a look at it later.

**Comment by morremeyer** [comment]
I checked the code, specifically https://github.com/integrations/terraform-provider-github/blob/950473879572717866c7a8eb8bc1cc4346e8fe76/github/resource_github_user_invitation_accepter.go#L27-L44. 

This just passes back the errors from the API client if any occurs - I would therefore revise my `bug(?)` as to me, changing this would be adding new functionality - the current one works as designed.

To make usage of the `github_user_invitation_accepter` easier, I propose to add a flag to enable ignoring 404 errors. With that, the resource won't error out when an invitation has already been accepted.
I'm planning to contribute a PR for that next week.

**Comment by kfcampbell** [comment]
@morremeyer that sounds awesome, thank you!

**Comment by morremeyer** [comment]
I looked into implementing both my proposals. I came to the following conclusions:

Implementing the flag to enable ignoring 404 errors is technically easy, I started that in #1469. However, writing the tests would take me a considerable amount of time since this would be the first test using a client to manually perform an action for the collaborator in the tests. (see also https://github.com/integrations/terraform-provider-github/pull/1469#issuecomment-1385154011). 

I therefore decided to not continue with this for now, if someone else wants to pick my work up, they are very welcome to do so.

Adding the capability to allow empty invitation IDs was a lot easier for me and is done in #1488. This will resolve all cases where invitations are handled **by terraform only**.

For cases where somebody accepts the invite **between the state refresh and the terraform apply**, the reported error with the 404 will still occur. 
I see this as an edge case since this is timing-dependent - if the invite is manually accepted **before** the state refresh, the 404s do not happen according to my understanding and what I've seen in our use case. I still think it is worth fixing that edge case, but for our use case #1488 is sufficient.
