### ISSUE TITLE
Unable to configure GitHub Pages

### ISSUE THREAD

**Issue by multani** [integrations/terraform-provider-github#1289]
### Terraform Version

```
$ terraform -v
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/integrations/github v4.31.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository`

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 1.2"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.0.0"
    }
  }
}

provider "github" {}

resource "github_repository" "test" {
  name = "test-tf-pages"

  pages {
    source {
      branch = "main"
      path   = "/"
    }
  }
}
```

### Debug Output

https://gist.github.com/multani/e3e2669148f1605a6b743121caae17fe

There's one output when the pages are being added, and one output when the pages are being un-configured.

### Expected Behavior

I can change the settings of the GitHub Pages for this repository.

### Actual Behavior

Note that:

* the same behavior happens at deletion, see [the `tf-apply-remove-pages.debug.log` gist](https://gist.github.com/multani/e3e2669148f1605a6b743121caae17fe#file-tf-apply-remove-pages-debug-log)
* it also happens with `4.31.0`
* it seems to be working as expected when the repository is created, but not when the repository configuration is _changed_

It fails with:

```
github_repository.test: Refreshing state... [id=test-tf-pages]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # github_repository.test will be updated in-place
  ~ resource "github_repository" "test" {
        id                          = "test-tf-pages"
        name                        = "test-tf-pages"
        # (29 unchanged attributes hidden)

      + pages {
          + source {
              + branch = "main"
              + path   = "/"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

github_repository.test: Modifying... [id=test-tf-pages]
╷
│ Error: PUT https://api.github.com/repos/multani/test-tf-pages/pages: 404 Not Found []
│ 
│   with github_repository.test,
│   on repo.tf line 1, in resource "github_repository" "test":
│    1: resource "github_repository" "test" {
│ 
╵

```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

* Seems to be connected to https://github.com/integrations/terraform-provider-github/issues/1198 but I'm using the new version

**Comment by mlitvinav** [comment]
I've run into the same issue on 5.8.0 and found this GitHub community discussion:
https://github.com/community/community/discussions/35595

Sadly as often with providers, its not a provider issue.
This problem occurs because GitHub Apps [are and will not be able to manage Pages](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#pages) on Repositories.

My current workaround is to import all repositories, delete all page entries from the pages array in the state file (keep an empty array) and not to manage GitHub Pages via Terraform. You may need to download your remote state to edit it...

**Comment by Luis-3M** [comment]
+1

**Comment by usmonster** [comment]
Duplicate of #777, no?

**Comment by highb** [comment]
The linked thread indicates that the vulnerable endpoint has been re-enabled and updated with authentication, so I believe this should be fixable now? https://github.com/orgs/community/discussions/35595#discussioncomment-4680098

**Comment by eccles** [comment]
I have recently tried managing pages via terraform nad get a panic:

╷
│ Error: Request cancelled
│ 
│   with module.repos["myrepo2"].github_repository.repo,
│   on ../modules/repos/main.tf line 11, in resource "github_repository" "repo":
│   11: resource "github_repository" "repo" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.repos["myrepo"].github_repository.repo,
│   on ../modules/repos/main.tf line 11, in resource "github_repository" "repo":
│   11: resource "github_repository" "repo" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.repos["rkvst-python"].github_repository.repo,
│   on ../modules/repos/main.tf line 11, in resource "github_repository" "repo":
│   11: resource "github_repository" "repo" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-github_v5.26.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 39 [running]:
github.com/integrations/terraform-provider-github/v5/github.expandPagesUpdate({0xc00097ee90?, 0x1291d78?, 0x6?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_repository.go:860 +0x379
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryUpdate(0xc0000d8700, {0x104a740?, 0xc000830a40})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_repository.go:726 +0x508
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0002a0640, 0xc000a86af0, 0xc000b2c020, {0x104a740, 0xc000830a40})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:326 +0x3e3
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000292c00, 0xc000bd58c8, 0x129cda6?, 0xf?)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000bc618, {0xc00040aaf0?, 0x4b8786?}, 0xc00040aaf0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1244f00?, 0xc0000bc618}, {0x15eb780, 0xc000ade810}, 0xc00040aa80, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x15ef648, 0xc0007024e0}, 0xc000ae0120, 0xc0003ff440, 0x1e0f6c0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x15ef648, 0xc0007024e0}, 0xc000ae0120, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-github_v5.26.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

task: Failed to run task "repos-apply": exit status 1

**Comment by heclemen** [comment]
we bumped into this issue after updating from 6.5.0 to 6.11.0 (tested also with 6.8 / 6.9 / 6.10)
```
      ~ pages {
            # (4 unchanged attributes hidden)

          + source {
              + branch = "main"
              + path   = "/"
            }
```
doesn't get updated, always shows on the terraform plan
