### ISSUE TITLE
"github_team_repository.write.0: At least one permission expected from permissions map."

### ISSUE THREAD

**Issue by benabineri** [integrations/terraform-provider-github#131]
### Terraform Version
Terraform v0.11.7
+ provider.github v1.1.0

### Affected Resource(s)

- github_team_repository

### Terraform Configuration Files
```hcl
resource "github_repository" "repository" {
  name         = "${var.name}"
  description  = "${local.description}"
  homepage_url = "${local.homepage_url}"

  private            = true
  has_issues         = true
  has_wiki           = false
  allow_merge_commit = false
  allow_squash_merge = true
  allow_rebase_merge = true
  has_downloads      = false
  auto_init          = true
  archived           = "${var.archived}"
}

resource "github_team_repository" "write" {
  team_id    = "${element(var.write_teams, count.index)}"
  repository = "${github_repository.repository.name}"
  permission = "push"

  count = "${var.write_teams_count}"
}
```

### Debug Output
Can provide.

### Panic Output
No panic.

### Expected Behavior
github_team_repository.write permission should be set.

### Actual Behavior
Fails with the error below (but only for some repos)

```
* module.<module name>.github_team_repository.write[0]: github_team_repository.write.0: At least one permission expected from permissions map.
```

### Steps to Reproduce
Try to create a github_team_repository.

Thanks.

**Comment by radeksimko** [comment]
Hi @benabineri 
thanks for the report.

I was unfortunately unable to reproduce the bug though. Do you mind providing the [debug log](https://www.terraform.io/docs/internals/debugging.html) from terraform commands you ran (minus any secrets)?

You can create a gist (instead of pasting it directly to the thread here). Also feel free to use our [GPG key](https://keybase.io/hashicorp) to encrypt it if you feel the need for it.

Thanks.
