### ISSUE TITLE
[MAINT]: CI Action does not run any tests

### ISSUE THREAD

**Issue by elliottpope** [integrations/terraform-provider-github#1385]
### Describe the need

ci.yml Action uses `make test` which no longer runs any tests. Instead we should use `make testacc` which runs the acceptance tests. Running these tests would have prevented issue https://github.com/integrations/terraform-provider-github/issues/1373

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
I completely agree! This is something that's been bothering me for a while. There's a few things that have been holding me back: 

- I don't have access to the currently-defined [acceptance testing accounts](https://github.com/integrations/terraform-provider-github/blob/main/.github/workflows/dotcom-acceptance-tests.yml#L23-L53), so we'll need to make new ones. 
- There are many tests which require a bespoke setup (e.g. a template repository set up with a certain structure, accounts set up a certain way, tests that need paid-for plans to execute) that we don't have good answers to now. It's probably best to not hold up the easily-available reliability gains by adding some automated acceptance testing, but I'd like to do something about this because it's not sustainable in the long term. Such requirements are not documented and not readily apparent.
- Many, many current tests are broken and will need to be removed wholesale or fixed, which is a labor-intesive task. 


@nickfloyd if I could only prioritize one initiative for the terraform provider, I'd pick this issue. Do you have thoughts about the above, or how we might go about getting it prioritized?
