### ISSUE TITLE
[FEAT]: Allow for enabling discussions on repos

### ISSUE THREAD

**Issue by nbaechtold** [integrations/terraform-provider-github#1442]
### Describe the need

Currently, it is not possible to enable GitHub Discussions on a repository due to the setting not being exposed though the `github_repository` resource.  

This means that anyone who wishes to manage their repositories with Terraform and leverage Discussions must enable them out-of-band.

It would be great to be able to enable them by exposing the value.

For example:

```hcl
resource "github_repository" "discussions-true" {
  name        = "discussions-true"
  visibility  = "private"
  has_issues = true
  has_discussions = true
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arunsathiya** [comment]
This can be closed because it's already fixed in https://github.com/integrations/terraform-provider-github/pull/1443. That PR didn't automatically close this issue because [it didn't meet the syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by kfcampbell** [comment]
Thanks @arunsathiya, closing now.
