### ISSUE TITLE
Is possible to update the settings of an existent repository without importing it in terraform?

### ISSUE THREAD

**Issue by l-lafin** [integrations/terraform-provider-github#1765]
We are using the provider to configure our existent repositories in order to standardize and secure all the configurations, this process is executed by a GitHub workflow. We'd like to update the repository settings such as 'Allow merge commits', 'Automatically delete head branches', etc for those existent repositories, but the only resource that I found allowing us to update them is 'github_repository' but this resource always try to create the repository and we don't want that. We also don't want to import the Terraform state, because we want to automate it as much as possible without human interference.

Is there any other resource that is able to update the repository settings instead of creating the whole repository? Or this would be a new feature request?

**Comment by devopsrick** [comment]
If you use terraform 1.5+ you can import via code and remove the manual human interaction required for importing.  Otherwise there are some settings such as branch protections that have separate resources. You would have to see if there are any covering the settings you want.  I would suggest looking through the resource documentation at: https://registry.terraform.io/providers/integrations/github/latest/docs
