### ISSUE TITLE
[BUG]: github_repository.ssh_clone_url returns unusable URI

### ISSUE THREAD

**Issue by landintrees** [integrations/terraform-provider-github#1842]
### Describe the issue

The URI provided by github_repository.ssh_clone_url (and I suspect other URLs like http_clone_url but have not tested them all) returns an invalid URI that has a colon instead of a slash after the domain.

i.e. URI should be:
`git@github.com/myorg/flux_repo.git`

URI returned:
`git@github.com:myorg/flux_repo.git`

Error returned when running terraform plan:
`invalid port ":myorg" after host`

### Terraform Configuration Files

```
data "github_repository" "flux" {
  full_name = "myorg/flux_repo"
}

data "flux_sync" "main" {
  target_path         = "clusters/${var.cluster_name}"
  url                 = "ssh://${data.github_repository.flux.ssh_clone_url}"
  branch              = "main"
  namespace           = "flux-system"
}
```

### Error output

```
╷
│ Error: expected "url" to be a valid url, got ssh://git@github.com:myorg/flux_repo.git: parse "ssh://git@github.com:myorg/flux_repo.git": invalid port ":myorg" after host
│ 
│   with module.flux.data.flux_sync.main,
│   on ../../../modules/flux/main.tf line 171, in data "flux_sync" "main":
│  171:   url                 = "ssh://${data.github_repository.flux.ssh_clone_url}"
│ 
╵
```

### Expected Output

`No changes. Your infrastructure matches the configuration.`

### Terraform Version

```
Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/fluxcd/flux v0.15.3
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/azuread v2.39.0
+ provider registry.terraform.io/hashicorp/azurerm v3.57.0
+ provider registry.terraform.io/hashicorp/github v5.32.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/microsoft/azuredevops v0.5.0
```

**Comment by nickfloyd** [comment]
Hey @landintrees thank you for reaching out!

So that value is actually in the correct format for cloning using SSH - see the REST API docs on [repositories](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28).  So in your example above:

`git@github.com:myorg/flux_repo.git`

`git` is the user (because GitHub uses this user for all Git SSH connections).
`github.com` is the hostname.

After the colon, `myorg/flux_repo.git` is the path to the specific Git repository.

SSH URIs with colons are typically used to denote paths on the remote host, especially when referring to repositories or files.
The colon here serves as a delimiter between the host and the path. This is distinct from how other URLs or URIs use slashes (/) to denote paths, primarily because the SSH syntax evolved in a slightly different context and has its unique conventions.

**Comment by landintrees** [comment]
Hi @nickfloyd, yes you're right. This is actually a problem with the way the flux provider is handling the URL, sorry for the noise.
