### ISSUE TITLE
[BUG]: Incorrect default hostname for tokenFromGhCli() function

### ISSUE THREAD

**Issue by jkstpierre** [integrations/terraform-provider-github#1905]
### Expected Behavior

The expected default hostname for `gh auth login` and its associated `gh auth token` cli command is github.com. When the provider initializes and there is no base_url specified in its configuration or in the environment, the auth token fetched from the GitHub CLI should use github.com as its hostname.

### Actual Behavior

The default hostname is currently set to `api.github.com` which is incorrect and prevents the provider from correctly authenticating with GitHub via the GitHub CLI

### Terraform Version

Terraform version: 1.5.7

### Affected Resource(s)

- provider.go

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by divergentdave** [comment]
I tested this out and debugged using the latest commit from main, 0c393c4fd3f57516809059c9720b962ccbd83d89, and I'm still seeing issues. I'm using the following minimal pair of Terraform modules.

```
# main.tf
terraform {
  backend "local" {}

  required_version = ">= 1.3.1"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.37.0"
    }
  }
}

provider "github" {
  owner = "..."
}

module "module" {
  source = "./module"
}

data "github_repository_environments" "environments" {
  repository = "..."
}
```

```
# module/main.tf
terraform {
  required_providers {
    github = {
      source = "integrations/github"
    }
  }
}

data "github_repository_environments" "environments" {
  repository = "..."
}
```

After specifying `dev_overrides`, adding a sleep, and compiling as suggested in `CONTRIBUTING.md`, I attached my debugger. In `providerConfigure()`, the value of `base_url` from the provider's resource data is `"https://api.github.com/"`. This gets passed as the argument to `tokenFromGhCli()`, and since `baseURL` isn't empty, the hostname `"api.github.com"` gets parsed out of it, instead of using the now-corrected fallback. Then, the spawned process fails as before.

I think it would be better to use the `isGithubDotCom` check later in `providerConfigure`, instead of checking for an empty string. It appears that the `base_url` property won't ever be empty, since it is set up in the schema with `schema.EnvDefaultFunc()` with a non-nil default value.

**Comment by nickfloyd** [comment]
@divergentdave You make a really good point.  Part of the challenge was around GHES | GHEC instances which have configs that generally should have a host provided - which is what [this](https://github.com/integrations/terraform-provider-github/pull/1906) sought to address.  However as you point out defaults to the `api.github.com` host from the provider data - which is what @nfx was addressing [here](https://github.com/integrations/terraform-provider-github/pull/1898); his PR that I naively closed (now reopened as I consider what you are saying).

If you're interested would you be up for picking this up and giving a shot at a fix?  I've got to finish some rounds on Octokit and will have to come back to this.  

Thank you for being incredible and trying out the scenario that you just did, such a good catch! ❤️

**Comment by nfx** [comment]
Yep, my PR is a rubber hammer compared to the steel hammer that was merged into main in the issue referenced by @nickfloyd 😉

I don't know how gh CLI behaves for non-github.com auth, so I'd suggest to loop in folks from GH CLI.

I'm just genuinely interested in not supplying a token to provider via env var, so I want this to work 🤷🏻‍♂️

As the author of a large TF provider, I could suggest either taking a dependency on gh CLI Go package or introducing a new field/env for non-github.com users.

**Comment by nfx** [comment]
@vilmibm may know best on the right strategy here

**Comment by nickfloyd** [comment]
@nfx I didn't mean any disrespect toward your efforts there... apologies, I was just thinking out loud as to how conflated our challenge is here.  Thank you for bringing others into the conversation.  There is a path to making it "work" I just want to favor making it "right" for the problem at hand.  Thanks again for all you and the others do for this communty ❤️.
