### ISSUE TITLE
[FEAT]: When new release can be expected?

### ISSUE THREAD

**Issue by VOVELEE** [integrations/terraform-provider-github#2049]
### Describe the need

The current release is one month old and during this time couple of PRs were merged which fix known bugs (e.g. #2001 )

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VOVELEE** [comment]
anyone?

**Comment by nickfloyd** [comment]
Hey @VOVELEE Apologies for the delay. We have a few breaking changes that we’ll need to bump the major for.  @kfcampbell was planning on rolling a release with all of our breaking changes after the holidays - HashiCorp has some conventions/recommendations around shipping breaking changes (which is why we batch them) - sorry for the delay.  I’ll chat with @kfcampbell today to see about cutting a new release.

**Comment by VOVELEE** [comment]
Thanks for the update @nickfloyd 

Fingers crossed for smooth breaking changes :)

**Comment by VOVELEE** [comment]
@nickfloyd thanks for the release.
It fixed my issue with environments as a charm :)
