### ISSUE TITLE
[BUG]: v6.1.0 is not on Terraform Provider Registry

### ISSUE THREAD

**Issue by nikolay** [integrations/terraform-provider-github#2191]
### Expected Behavior

Versions v6.1.0 should be available on the Terraform Provider Registry.

### Actual Behavior

I get:
```
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider integrations/github: no available releases match the given constraints 6.1.0
╵
```

### Terraform Version

Terraform v1.7.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/tls v4.0.5
+ provider registry.terraform.io/integrations/github v6.0.1

### Affected Resource(s)

- github provider

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stevehipwell** [comment]
CC @kfcampbell

**Comment by kfcampbell** [comment]
This is bizarre. The logs from the [latest release](https://github.com/integrations/terraform-provider-github/actions/runs/8210977480) don't look meaningfully different to the [logs from the previous successful v6.0.1 release](https://github.com/integrations/terraform-provider-github/actions/runs/8148750837), and all the normal release artifacts have been successfully published.

In the past when releases haven't appeared on the registry, it's been due to the release workflow failing and the artifacts not being published on the GitHub releases page, which isn't the case here. I've reached out to Hashicorp to see if they can shed any light on the issue.

**Comment by kfcampbell** [comment]
Hashicorp has informed me they've had an intermittant outage last week that affected some new release publishes, and we're looking into steps to resync the release to the registry.

**Comment by stevehipwell** [comment]
Looking good here too.

**Comment by kfcampbell** [comment]
They've performed a resync and picked up the new release. I'm going to close out this issue.
