### ISSUE TITLE
It is possible to create duplicate `github_repository_collaborator` resources

### ISSUE THREAD

**Issue by gdavison** [integrations/terraform-provider-github#319]
It is possible to create duplicate `github_repository_collaborator` resources if the same username is used twice. The GitHub API appears to return the same information, as the invitation IDs are the same.

I discovered this in an existing Terraform configuration while converting from list & `count` to set & `for_each`.

```
$ terraform version
Terraform v0.12.18
+ provider.github v2.2.1
```

### Affected Resource(s)

- github_repository_collaborator

### Example
```hcl
variable "collaborators" {
    type = list(string)

    default = [
        "jdoe",
        "jdoe",
    ]
}

resource "github_repository_collaborator" "collaborator" {
  count      = length(var.collaborators)
  repository = github_repository.provider.name
  username   = var.collaborators[count.index]
}
```

### Expected Behavior
There should be an error message stating that `jdoe` has already been invited.

### Actual Behavior
There were two records, `github_repository_collaborator.collaborator[0]` and `github_repository_collaborator.collaborator[1]`, with the same `username` and `invitation_id` parameters.

**Comment by kpfleming** [comment]
In order to do that the provider would have to query the existing collaborator list during repository creation, instead of just calling `AddCollaborator`, but if it did that then it would not work with repositories that are being imported and already have outstanding collaborator invitations.

It may not be possible for the provider to detect the situation where an invitation exists (or the user has already accepted an invitation) *and* the invitation was generated by the provider.

**Comment by jcudit** [comment]
A couple of options:
- check for duplicate invitations and emit a warning if one is found without erroring out
- check for duplicate invitations and error out if one is found, while providing a configuration option to disable this behaviour
