### ISSUE TITLE
Using different GITHUB_TOKENS cause repository_deploy_keys to always be created

### ISSUE THREAD

**Issue by Geethree** [integrations/terraform-provider-github#407]
### Terraform Version
```
$ terraform providers -v
Terraform v0.12.24
+ provider.aws v2.55.0
+ provider.github v2.5.0
```

### Affected Resource(s)
- [github_repository_deploy_key](https://www.terraform.io/docs/providers/github/r/repository_deploy_key.html)

### Expected Behavior
If a configuration contains a _github_repository_deploy_key_ resource `foo`, when different users using their own github token running terraform plan|apply will not require any changes for resource `foo`.

### Actual Behavior
- If after user A uses their personal github token to create the _github_repository_deploy_key_ resource `foo`.
- Then when user B then uses their personal github token to plan/apply the configuration the resource `foo` will need to be created, not recreated.
- Finally, if user B then tries to apply the configuration it fails as github rightly complains that the repository already contains a deploy key with the name provided in the configuration.

**Comment by anGie44** [comment]
hi @Geethree!  could you please provide a sample configuration and/or debug logs of the scenario you are describing? it seems the terraform configs would differ in the `provider` block if the user github token is explicitly passed there or is the token set as an ENV var?

**Comment by Claywd** [comment]
@Geethree On first glance I think what you are experiencing is expected behavior... but after reading it very carefully I think you are trying to say that the "github_repository_deploy_key" never actually changes and the only thing changing it he PAT used to authenticate against github from terraform. 

If that is correct and If you wouldn't mind, could you attach the statefile, stacktrace, & resource definition you are using?

**Comment by Geethree** [comment]
OK Lets say we have these resources..

```
resource "tls_private_key" "github_deploy_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "github_repository_deploy_key" "foobar" {
  title      = foobar
  repository = bezos/rocks
  key        = tls_private_key.github_deploy_key.public_key_openssh
  read_only  = "true"
}
```

Assume all users are instantiating the github provider with their own _personal access token_.

When user A first creates all of these resources, a GH deploy key is created for the repository called `foobar` which is created by `@userA`.

If user B then goes to run the configuration again, terraform states that it must create - not update - the deploy key resource `foobar`. If.. the user B applies the configuration the apply fails as a deploy key `foobar` already exists for the repository.

I'd expect for this resource to.. check the name and fingerprint of the key and notice that both the deploy key name and the deploy key finger print match to say.. this resource already exists no need to change it.

So to me.. it seems that the deploy key is some how related to the username that both owns the personal access token and created the deploy key.

THis isn't really easy to test as you need two github accounts with personal access tokens trying to create a deploy key for a repo.

**Comment by anGie44** [comment]
Hi @Geethree! I was able to reproduce this but noted that it depends on user and/or team permissions. Some of the examples I tried:
* if `user B` is a member of the organization (owner) of the repository in question but only has read or write permissions, when user B applies the config, the `plan` phase indicates a deploy key needs to be created and `apply` fails as you've described. However, if `user B` has `admin` access within the organization, when `user B` applies the config, the tf plan refreshes the state and recognizes there are no changes to be made. 
* if `user B` is part of a team that has direct access to the repository in question, the team must have `admin` privileges for `user B` to be able to run the config and have the terraform plugin recognize the deploy key created by `user A` exists and the infrastructure does not need to be created or updated. 
* similar to the bullet point above, if `user B` has direct access to the repository in question, the user must have `admin` privileges to be able to run the config and have the terraform plugin recognize the deploy key created by `user A` exists and the infrastructure does not need to be created or updated.

**Comment by jwenz723** [comment]
I am currently experiencing this issue.

In my situation the deploy key is being created on a repository which is in an organization. I am an organization owner. The other users that are executing terraform have the `admin` role on the repository. 

There are 2 scenarios which trigger the `github_repository_deploy_key` resource to be recreated in my experience. I will describe the 2 scenarios with `User A` acting as an `organization owner` and `User B` acting as an `admin` on the repository.

### Scenario 1

1. `User A` executes `terraform apply` and the `github_repository_deploy_key` resource gets created
2. `User B` executes `terraform apply`, this triggers the `github_repository_deploy_key` resource to be created without any indication that the already existing key will be destroyed. The resource creation fails due to the fact that it already exists.

### Scenario 2

1. `User B` executes `terraform apply` and the `github_repository_deploy_key` resource gets created
2. `User A` executes `terraform apply`, this triggers the `github_repository_deploy_key` resource to be created without any indication that the already existing key will be destroyed. The resource creation fails due to the fact that it already exists.

### Logs

In both scenarios the following logs occur.

#### during `terraform plan`

```terraform
  # module.test.github_repository_deploy_key.test[0] will be created
  + resource "github_repository_deploy_key" "test" {
      + etag       = (known after apply)
      + id         = (known after apply)
      + key        = <<-EOT
            ssh-rsa redacted....
        EOT
      + read_only  = false
      + repository = "myrepository"
      + title      = "mykey"
    }
```

#### during `terraform apply`

```terraform
Error: POST https://api.github.com/repos/myorg/myrepository/keys: 404 Not Found []

  on .terraform/modules/test/modules/test/github.tf line 15, in resource "github_repository_deploy_key" "test":
  15: resource "github_repository_deploy_key" "test" {
```


The only way to get around this issue for me up to now has been to manually delete the deploy key from the repository before executing terraform.

**Comment by logicbomb421** [comment]
Hello,

I am also experiencing this with the `github_branch_protection` and `github_repository` resources.

I created/imported my repository with existing protections using my own all-scopes PAT. When the plan then runs in CI using a more restricted PAT, the plan indicates a create (not delete/create) will take place for the existing branch protections.

The plan also indicates some repository settings will be updated that are already set correctly:
```hcl
  ~ resource "github_repository" "repo" {
      ~ allow_merge_commit     = false -> true
      ~ allow_squash_merge     = false -> true
      ~ delete_branch_on_merge = false -> true
        id                     = "my-repo"
        name                   = "my-repo"
        # (23 unchanged attributes hidden)
    }
```

While the repo update would likely be a no-op, the attempt to create existing branch protections fails.

**Comment by dkowis** [comment]
I have this problem, but I don't have to change any Github user tokens. 

I grab my deploy key from AWS SSM, and so it's provided as data. Once it's been created. The Github repo deploy key is always "recreated" even though the content hasn't changed. I've verified with the UI in Github, it's all the same signature and everything. 

There's definitely something fishy with the deploy key resource. My organization secrets resource works great, however.

**Comment by hbouissoumer** [comment]
any update on this?

**Comment by sthompson0** [comment]
I'm running into a similar situation. We actuate our infra with atlantis and the GITHUB_TOKEN changes over time. The resource "github_repository_deploy_key" shows up in plan output  with changes and is causing cognitive overhead to end users and PR reviewers to understand why it's showing up since the key already exists and shouldn't need to be changed. It's still unclear to me why terraform thinks anything needs to change for an existing resource that had no changes.
