### ISSUE TITLE
Adding auto_init=true does not trigger changes to uninitialized repositories

### ISSUE THREAD

**Issue by djfinnoy** [integrations/terraform-provider-github#548]
### Terraform Version
```
Terraform v0.12.28
+ provider.github v2.9.2
```
### Affected Resource(s)
Please list the resources as a list, for example:
- `github_repository`

### Expected Behavior
When adding `auto_init=true` to an existing, uninitialized repository, and applying the terraform plan; the repository should become initialized.

I think what's missing here is that changes to `auto_init` should require replacement, like many other inputs to `github_repository` do (eg. `template`).

### Actual Behavior
The repository does not become initialized, even though terraform picks up on the fact that `auto_init` has changed from `false` to `true`:
`auto_init` has no effect on pre-existing repositories, even when they are not initialized.

If we delete the pre-existing repository, and create it again with `auto_init=true` present from the very first `terraform apply`, the repository gets created and initialized as expected.

### Steps to Reproduce
1. Create a repository without `auto_init=true`, using the Github provider.
2. Realize you forgot to add `auto_init=true`, change code, run `terraform apply` again
3. Terraform plan indicates that the value of `auto_init` will change, but after the plan is applied, the repository has not been initialized.
4. Realize you do not have permission to delete repositories from your organizations GitHub.
5. Ask administrator to delete the repository, run your Terraform code again with `auto_init=true` included from the get-go.

**Comment by jcudit** [comment]
> `auto_init` has no effect on pre-existing repositories, even when they are not initialized.

I agree this is a frustrating sequence to follow.  However, my understanding of `auto_init` is that GitHub will only consider it upon initial repository creation.  A solution could possibly be hacked together to initialize a repository by mixing the `github_repository_file` and `github_default_branch`.

I will interpret this request as "add `ForceNew`" to the `auto_init` schema field so that changes to it will trigger a re-creation of the overall repository:

https://github.com/terraform-providers/terraform-provider-github/blob/cfaf4d05bc8be6c88d38517282d9b563e4a63f73/github/resource_github_repository.go#L96-L99

**Comment by nocode99** [comment]
What about setting this as a default option? There's a few other github settings that can't be enabled unless a file has been committed. I'm on terraform `0.14.4` and using the latest github provider `4.12.2`
