### ISSUE TITLE
Do not destroy the repository when you change the repository name

### ISSUE THREAD

**Issue by smorimoto** [integrations/terraform-provider-github#616]
Is this intentional?

**Comment by jcudit** [comment]
Unintentional.  We should support renaming a repository without having to destroy it.  Will track this for the next batch of `repository` resource updates.

**Comment by smorimoto** [comment]
I also changed the local name at the same time, is that probably the cause? Ideally, even if you change both the local name and the repository name, it should not be destroyed.

**Comment by k24dizzle** [comment]
Hi, I went ahead and gave this a shot here: https://github.com/integrations/terraform-provider-github/pull/699. Would appreciate any feedback!

**Comment by smorimoto** [comment]
Cool, I will take a look at it when I have much spare time 🙂

**Comment by majormoses** [comment]
This is actually quite an old issue and something that was not exactly intentional and more a set of unfortunate set of limitations of the (documented) api. See #55 for more information.

**Comment by k24dizzle** [comment]
Seems like the main issue here is that the `github_repository` resource uses the `name` as the id of the resource, which we want to change, rather than the `repo_id` which shouldn't change. 

I wonder how far we could get by removing the `ForceNew` attribute from the `name` field. In my testing (in my PR above), removing that allows you to rename a repository. Behind the scenes, it will assign the resource a new id, since there is a new name, but are there any implications of changing the id of a terraform resource?

cc: @jcudit

**Comment by jcudit** [comment]
Removing (or making configurable) the `ForceNew` is a reasonable first step to get this functionality.  My worry too is with unforeseen effects of changing the ID of a `repository` resource.  I recommend we enable this behaviour defaulted to off so that consumers can test or ignore the feature at their judgement.  

Aiming to land some suggestions on the attached PR to keep it moving.

**Comment by devinrsmith** [comment]
I think this issues has been fixed by #699 

I've planned out a run, and now I see `github_repository` being updated in-place :)

Unfortunately, I think there are a lot of other resources that reference the repository name, and would be better served by referencing a repository id (#744).

From our own usage, we see the following resources planned to be destroyed during a repo rename: `github_branch`, `github_branch_default`, `github_branch_protection_v3`, `github_repository_collaborator`, and `github_team_repository`. (There are probably other relevant resources that need to be updated, that we don't use.)

I'm assuming I'll need to go through a rename and manual import step instead of a normal terraform apply to resolve this currently.

**Comment by Caleb-Hoffman** [comment]
Hi @kfcampbell, just curious if there are any updates on this?

**Comment by mwarkentin** [comment]
@Caleb-Hoffman according to #55 I think this might be resolved?

**Comment by kfcampbell** [comment]
Closing as #55 is closed; please let me know if this is not the case.
