### ISSUE TITLE
Planning an imported branch protection requires it to be replaced

### ISSUE THREAD

**Issue by k24dizzle** [integrations/terraform-provider-github#622]
Not sure if this is expected behavior or a bug, but opening an issue to open discussion!

### Terraform Version
`Terraform v0.13.5`

### Affected Resource(s)
`github_branch_protection`

### Terraform Configuration Files
```
provider "github" {
  organization = "kzhaotest"
}

resource "github_branch_protection" "branch" {
  repository_id  = "test2"
  pattern        = "main"
  enforce_admins = true
}
```

### Debug Output
https://gist.github.com/k24dizzle/7fc2e17296c3eb740be89d0a634bc929

### Expected Behavior
I tried to import a branch protection and then ran a terraform plan with the existing terraform config to make sure that my configuration matched the imported state. I expected the terraform plan to return that there were no resources to be modified/added/destroyed.
```
  terraform init
  terraform import github_branch_protection.branch test2:main
  terraform plan
```

### Actual Behavior
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # github_branch_protection.branch must be replaced
-/+ resource "github_branch_protection" "branch" {
        enforce_admins         = true
      ~ id                     = "MDIwOkJyYW5jaFByb3RlY3Rpb25SdWxlMTg1MjkzNDA=" -> (known after apply)
        pattern                = "main"
      - push_restrictions      = [] -> null
      ~ repository_id          = "MDEwOlJlcG9zaXRvcnkzMTg5MzcwNzg=" -> "test2" # forces replacement
        require_signed_commits = false
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

According to the [docs](https://github.com/terraform-providers/terraform-provider-github/blob/master/website/docs/r/branch_protection.html.markdown), the repository_id can take in `The name or node ID of the repository associated with this branch protection rule.` But here it seems like it wants to destroy and recreate the branch protection to replace the node id with the name of the repository.

### Steps to Reproduce
See the gist. The repository + terraform I tested on is located here: https://github.com/kzhaotest/test2

**Comment by faultylee** [comment]
We're also facing the same problem, it applies to all the argument that accept `[]`:
-  `push_restrictions`
- `dismissal_restrictions`
- `contexts`
Blocks are affected as well
- `required_status_checks`
- `required_pull_request_reviews`

Taking `push_restrictions` as example:
- Not defining `push_restrictions`
- `push_restrictions=[]`
- `push_restrictions=null`
All above will result in ` - push_restrictions      = [] -> null` when planning. In the state file, `push_restrictions = []`. 

I don't understand `go` enough to know where the problem is, but I suspect internally whenever a default value is present for these arguments, the code set it to `null`, which then conflict when what was read from Github API as `[]`

**Comment by faultylee** [comment]
I managed to fix this using `repository_id = github_repository.repo.node_id`
