### ISSUE TITLE
Can't import github_branch_protection using repository node_id:branch pattern

### ISSUE THREAD

**Issue by faultylee** [integrations/terraform-provider-github#671]
### Terraform Version
- v0.14.3
- `terraform-provider-github_v4.2.0`

### Affected Resource(s)
- branch_protection

### Debug Output
I had to masked the `org`
https://gist.github.com/faultylee/0fa1a34cade6ee047f9e81967fd93993

### Expected Behavior
Import of branch_protection works with `node_id`

### Actual Behavior
`node_id` use during import was interpreted as repo_name

### Steps to Reproduce
- `terraform init`
- `terraform import github_branch_protection.repo_branch_protection 'MDEwOlJlcG9zaXRvcnkzMzI2ODM4OTc=:main'`

### References
- See #597 although it's closed but the issue wasn't 100% resolve. I think the existing flow of using the `node_id` has issue and wasn't tested

**Comment by tibbes** [comment]
Thanks for the bug report @faultylee. The fix has been merged, so it will be in the next release.

**Comment by bateller** [comment]
> Thanks for the bug report @faultylee. The fix has been merged, so it will be in the next release.

@tibbes Are we sure this is resolved? I'm still having issues importing with `node_id`

```
Initializing the backend...

Initializing provider plugins...
- Finding integrations/github versions matching "~> 4.0"...
- Installing integrations/github v4.5.1...
- Installed integrations/github v4.5.1 (signed by a HashiCorp partner, key ID 38027F80D7FD5FB2)
```

```
$ terraform import github_branch_protection.some_repo 'MDEwOlJlcG9zaXRvcnkxMTE1NjgzNTQ=:master'
github_branch_protection.some_repo: Importing from ID "MDEwOlJlcG9zaXRvcnkxMTE1NjgzNTQ=:master"...

Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```

**Comment by tibbes** [comment]
@bateller, it looks like there is some missing error checking. Apologies.

I can reproduce that message, but only when the branch protection rule does not exist. I will open a pull request to fix that. Please can you verify that the `master` branch is actually protected on that repository?

**Comment by bateller** [comment]
@tibbes Yes, I can confirm `master` didn't have branch protection. 

Sorry about that (I didn't have Admin permission on the repo I was importing)

Tried on another repo within the same org (and with the same Terraform setup) with a repo I had Admin access on and imported branch protection for `master` successfully.

It appears this issue (and https://github.com/integrations/terraform-provider-github/issues/597) are failing for me due to not checking if the imported resource exists on Github (which would be a nice check for those of us using Terraform to manage Github when we don't have direct Admin access)

**Comment by tibbes** [comment]
I've opened #721 to fix the error message. Thanks for reporting.
