### ISSUE TITLE
github_branch data sources are not working in organisation context

### ISSUE THREAD

**Issue by rcornu** [integrations/terraform-provider-github#902]
Hi,

It seems that github_branch data sources are not working in an organisation context.

### Terraform Version
Terraform v1.0.6

### Github Provider Version
registry.terraform.io/hashicorp/github 4.14.0

### Affected Resource(s)
- data.github_branch

### Terraform Configuration Files
```hcl
data "github_branch" "this" {
  repository = "myorganisation/myrepository"
  branch     = "main"
}

output "github_branch" {
  value = data.github_branch.this
}
```

### Debug Output
```bash
github_branch       = {
      + branch     = null
      + etag       = null
      + id         = null
      + ref        = null
      + repository = null
      + sha        = null
 }
```

### Expected Behavior
Resource should handle repository in an organisation, maybe with a repository_full_name attribute (org/name format).

### Actual Behavior
Provider is requesting `https://api.github.com/repos/USER/myorganisation/myrepository/git/ref/heads/main`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
1. `terraform apply`

**Comment by aidan-mundy** [comment]
@rcornu @jcudit This isn't a bug per-se... 

At the moment, the "intended" way to do this is with a provider configuration (either the main one or an alias) that has the `owner` variable set to the organization (e.g. `myorganisation`). The vast majority of resources in this provider work on the assumption that the owner of the datasource/resource is/will be the `owner` from the provider. Naming of resources is handled the same way, where the repo name is `repo` instead of `owner/repo`.  

A `repository_full_name` argument (similar to `full_name` [here](https://registry.terraform.io/providers/integrations/github/latest/docs/data-sources/repository)) would be a welcome addition to the provider's feature set (and an amazing "good-first-issue"). However, my preferred solution to this would be to change the provider's `owner` variable to `default_owner` and offer an optional `owner` argument in every resource and datasource.

**Comment by thpang** [comment]
Updates or status? Is this one going to be fixed? It's been out there for sometime. Thx in advance.
